name: Grading

on:
  pull_request:
    branches: [ main ]

jobs:
  grading-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 2
          token: ${{ secrets.GH_DB_TOKEN }}
      - name: Show submodule updated
        run: git diff --name-only HEAD^
      - name: Check clean
        run: ./5-grading-tests/scripts/check_clean.sh
      - name: Test
        run: ./5-grading-tests/scripts/test.sh
